excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://binsearch.github.io
title: ramblings of a developer
email: rohithkishan.krs@gmail.com
author: rohith kishan
description: binsearch's blog
paginate: 3
google_analytics: 50160044